//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NNR.Context.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionDetail
    {
        public int TrnzDetailID { get; set; }
        public int TrnzHdrID { get; set; }
        public int TrnzTypeAndSubID { get; set; }
        public int TrnzType { get; set; }
        public string TrnzLiveID { get; set; }
        public string TrnzLiveDescription { get; set; }
        public Nullable<System.DateTime> TrnzLiveDate { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
    }
}
